name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          make install
      - name: lint code
        run: |
          make lint
      - name: Run tests
        run: |
          make test
      - name: format code
        run: |
          make format